name: "codestyle"
description: "Runs python code style checklist (black, flake8, mypy and bandit)"
inputs:
  workdir:
    description: "working directory"
    required: false
    default: "."
  requirements_file:
    description: "requirements file"
    required: false
    default: "requirements.txt"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.5"
    - name: Install checklist dependencies
      shell: bash
      run: |
        pip install \
          black==25.1.0 \
          flake8==7.3.0 \
          bandit==1.8.5 \
          mypy==1.16.1
    - name: Install given dependencies
      shell: bash
      run: |
        cd ${{ inputs.workdir }}
        pip install -r ${{ inputs.requirements_file }}
    - name: "Bandit"
      shell: bash
      run: bandit -c .bandit.yaml -rv ${{ inputs.workdir }}
    - name: "Mypy"
      shell: bash
      run: mypy --config-file .mypy.ini ${{ inputs.workdir }}
    - name: "Black"
      shell: bash
      run: black --check ${{ inputs.workdir }}
    - name: "Flake8"
      shell: bash
      run: flake8 ${{ inputs.workdir }}
