name: pr

on:
  pull_request:
  workflow_dispatch:

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: Creadentials search in source code - TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.69.0
      - name: Python codestyle
        uses: ./.github/actions/codestyle
